-- 코드를 입력하세요
SELECT USER.USER_ID, USER.NICKNAME, CONCAT(USER.CITY, ' ', USER.STREET_ADDRESS1, ' ', USER.STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTRING(USER.TLNO, 1,3), '-', SUBSTRING(USER.TLNO, 4, 4), '-', SUBSTRING(USER.TLNO, 8)) AS 전화번호
FROM USED_GOODS_BOARD BOARD JOIN USED_GOODS_USER USER
ON BOARD.WRITER_ID = USER.USER_ID
GROUP BY BOARD.WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY USER.USER_ID DESC;

