-- 코드를 입력하세요
SELECT USU.USER_ID, USU.NICKNAME, CONCAT(USU.CITY, " ",USU.STREET_ADDRESS1," ",USU.STREET_ADDRESS2) "전체주소", CONCAT(LEFT(TLNO, 3), '-', SUBSTRING(TLNO,4,4), '-', RIGHT(TLNO,4)) "전화번호"
FROM USED_GOODS_BOARD UGB JOIN USED_GOODS_USER USU
ON UGB.WRITER_ID = USU.USER_ID
GROUP BY UGB.WRITER_ID
HAVING COUNT(UGB.WRITER_ID) >= 3
ORDER BY USU.USER_ID DESC;