-- 코드를 입력하세요
SELECT BOARD.WRITER_ID, USER.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS BOARD JOIN USED_GOODS_USER AS USER
ON BOARD.WRITER_ID = USER.USER_ID
WHERE BOARD.STATUS = "DONE"
GROUP BY BOARD.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;
