-- 코드를 입력하세요
SELECT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE MONTH(CRCRH.START_DATE) = 10 AND CRCC.CAR_TYPE = "세단"
GROUP BY CRCRH.CAR_ID
ORDER BY CRCC.CAR_ID DESC;